name: boss_brawler
description: >-
  Train your negotiation skills to become a master deal-maker in any situation. Boss Brawler puts you in realistic, high-stakes bargaining scenarios—whether you're haggling over a salary, closing a major sales contract, or settling a dispute between teams.
publish_to: none
version: 0.0.1+1
environment:
  sdk: ^3.7.0
  flutter: '>=3.27.0-0'

dependencies:
  flutter:
    sdk: flutter
  flutter_ai_toolkit:
    path: ..
  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.4.3
  cloud_firestore: ^5.6.6 
  firebase_core: ^3.4.0
  firebase_auth: ^5.0.0
  firebase_vertexai: ^1.0.1
  google_sign_in: ^6.2.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  go_router: ^14.2.8
  uuid: ^4.5.1
  path: ^1.9.0
  path_provider: ^2.1.4
  flutter_markdown: ^0.7.4+1
  google_fonts: ^6.2.1
  retry: ^3.1.2
  future_builder_ex: ^5.0.0
  split_view: ^3.2.1

  idb_shim: ^2.6.5+1
  http: ^1.3.0
  audioplayers: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.10
  flutter_launcher_icons: "^0.14.3"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/recipes_default.json
    - assets/halloween-bg.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpeg"

