// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOK0gt0PhwxM1sWGD6LE2yjrrCuxt-mvE',
    appId: '1:750386372057:web:4df58b40bdd39d5132cdc8',
    messagingSenderId: '750386372057',
    projectId: 'boss-brawler',
    authDomain: 'boss-brawler.firebaseapp.com',
    storageBucket: 'boss-brawler.firebasestorage.app',
    measurementId: 'G-LF644S311X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-DhNIY-AyL28lXdisCKen775AdyG_Csg',
    appId: '1:750386372057:android:093bb9675eda934732cdc8',
    messagingSenderId: '750386372057',
    projectId: 'boss-brawler',
    storageBucket: 'boss-brawler.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACA3yeDKUPVT1SbfLjsX9jfig1Vpsan60',
    appId: '1:750386372057:ios:2675ae408b9b474732cdc8',
    messagingSenderId: '750386372057',
    projectId: 'boss-brawler',
    storageBucket: 'boss-brawler.firebasestorage.app',
    iosBundleId: 'com.brawler.app',
  );
}
